services:
- type: web
  name: lpdrz-proxy
  env: docker
  repo: https://github.com/lpformedrz123/拉夫梅德兹.git
  dockerfilePath: Dockerfile
  region: singapore # 建议选择 singapore 或 oregon
  plan: free # 使用 free 免费计划进行验证
  port: 3000
  envVars:
  - key: UUID
    value: 41d0467f-d430-4d5c-8c6f-0ecdce9cff09
  - key: CFIP
    value: lpformedrz.330329.xyz
